### ISSUE TITLE
Question about noise sources in SNR_25 dataset

### ISSUE THREAD

**Issue by starmoon-1134** [xixi219/MOS#1]
Could you please clarify the origin of noise in the SNR_25 subset? Does it include real-world recorded noise similar to the DEMAND dataset, or is it synthetically generated? Any information on the noise types and sources would be greatly appreciated.

**Comment by xixi219** [comment]
The noise in the SNR_25 subset is synthetically generated, not from real-world recordings. The noise types are artificially created to simulate different acoustic environments.

**Comment by starmoon-1134** [comment]
Thank you for your quick response. It was helpful to me.
